debug: false

processing:
  async: true
  cleanup-old-frames: true

limits:
  max-width: 256
  max-height: 256
  max-frames: 500

cache:
  enabled: true

console:
  colored-output: true

resourcepack:
  serve: true
  port: 8765
  host: ""

web:
  enabled: true
  port: 8766

itemsadder:
  namespace: igif
  auto-reload: true